name: release

on:
  push:
     branches: 'feature123'

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Get current year
       id: year
       run: echo "::set-output name=year::$(date +'%Y')"
       
     - name: Get current month
       id: month
       run: echo "::set-output name=month::$(date +'%m')"
       
     - name: Get current date
       id: day
       run: echo "::set-output name=day::$(date +'%d')"    
       
     - name: Print current year
       id: yearValue
       run: echo "${{steps.year.outputs.year}}"
 
     - name: Print current month
       id: monthValue
       run: echo "${{steps.month.outputs.month}}" 
       
         
     - name: Fetch tag
       id: tag
       run: |
             echo "::set-output name=tag::$(git describe --tags `git rev-list --tags --max-count=1`)"
     - name: Test tag
       run: |       
             echo "${{steps.tag.outputs.tag}}"    
             
     - name: Logic
       id: logic
       uses: actions/github-script@v1.1
       env:
         PR_NUMBER: ${{ github.event.pull_request.number }}
         CURRENT_VERSION: ${{steps.tag.outputs.tag}}
       with:
         github-token: ${{ secrets.MY_GITHUB_TOKENS }}
         script: |
           versionSyntax = (CURRENT_VERSION =~ /^(?<major>202\d)\.(?<minor>\d)\.(?<patch>\d+)$/)
           echo ${ versionSysntax }

             
       
       