name: release

on:
  push:
     branches: 'feature123'

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Get current date
       id: date
       run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
     - name: Print current date
       id: dateValue
       run: echo "${{steps.date.outputs.date}}"
     - name: Test with environment variables
       run: echo $TAG_NAME - $RELEASE_NAME
       env:
         TAG_NAME: nightly-tag-${{ steps.date.outputs.date }}
         RELEASE_NAME: nightly-release-${{ steps.date.outputs.date }}
         
     - name: Fetch year
       id: get-year
       uses: actions/github-script@0.9.0
       with:
         script: |
           const year = ${{ steps.date.outputs.date }}.value.split('-')[1]
           echo "${{year}}"
           core.setOutput('year', year)
     #- run: echo "${{ steps.get-year.outputs.year }}"    
     - name: Print current date
       id: dateValue
       run: echo "${{ steps.get-year.outputs.year }}"  
       