name: release

on:
  push:
     branches: 'feature123'

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       with:
         fetch-depth: 0
     - name: Fetch utils
       id: utils
       run: |
             echo "::set-output name=year::$(date +'%Y')"
             echo "::set-output name=month::$(date +'%m')"
             echo "::set-output name=tago::$(git fetch origin +refs/tags/*:refs/tags/*)"
             echo "::set-output name=tag::$(git describe --tags `git rev-list --tags --max-count=1`)"
     - name: Test tag
       run: |       
             echo "${{steps.utils.outputs.year}}"
             echo "${{steps.utils.outputs.month}}" 
             echo "${{steps.utils.outputs.tag}}"    
             
     - name: Split version code
       uses: xom9ikk/split@v1
       id: split
       with:
         string: ${{steps.utils.outputs.tag}}
         separator: .
         limit: -1
         
     - name: Some other action
       id: printv
       run: |
         echo "::set-output name=major::${{ steps.split.outputs._0 }}"  
         echo "::set-output name=minor::${{ steps.split.outputs._1 }}"  
         echo "::set-output name=patch::${{ steps.split.outputs._2 }}"             

             
       
       