name: release

on:
  push:
     branches: 'feature123'

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Get current year
       id: year
       run: echo "::set-output name=year::$(date +'%Y')"
       
     - name: Get current month
       id: month
       run: echo "::set-output name=month::$(date +'%m')"
       
     - name: Get current date
       id: day
       run: echo "::set-output name=day::$(date +'%d')"    
       
     - name: Print current year
       id: yearValue
       run: echo "${{steps.year.outputs.year}}"
 
     - name: Print current month
       id: monthValue
       run: echo "${{steps.month.outputs.month}}" 
       
         
     - name: Fetch tag
       id: tag
       run: echo "::set-output name=tag::$(git fetch origin +refs/tags/*:refs/tags/*)"
     - name: Test tag
       run: echo "${{steps.tag.outputs.tag}}"        
       
       