name: release

on:
  push:
     branches: 'feature123'

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Get current year
       id: year
       run: echo "::set-output name=year::$(year +'%Y')"
       
     - name: Get current month
       id: month
       run: echo "::set-output name=month::$(month +'%m')"
       
     - name: Get current date
       id: day
       run: echo "::set-output name=day::$(day +'%d')"    
       
     - name: Print current year
       id: yearValue
       run: echo "${{steps.year.outputs.year}}"
 
     - name: Print current month
       id: monthValue
       run: echo "${{steps.month.outputs.month}}" 
       
       
     - name: Test with environment variables
       run: echo $TAG_NAME - $RELEASE_NAME
       env:
         TAG_NAME: nightly-tag-${{ steps.date.outputs.date }}
         RELEASE_NAME: nightly-release-${{ steps.date.outputs.date }}
       
       