name: release

on:
  push:
     branches: 'feature123'

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Get current year
       id: year
       run: echo "::set-output name=year::$(date +'%Y')"
       
     - name: Get current month
       id: month
       run: echo "::set-output name=month::$(date +'%m')"
       
     - name: Get current date
       id: day
       run: echo "::set-output name=day::$(date +'%d')"    
       
     - name: Print current year
       id: yearValue
       run: echo "${{steps.year.outputs.year}}"
 
     - name: Print current month
       id: monthValue
       run: echo "${{steps.month.outputs.month}}" 
       
         
     - name: Fetch tag
       id: tag
       run: |
             echo "::set-output name=tag::$(git describe --tags `git rev-list --tags --max-count=1`)"
     - name: Test tag
       run: |       
             echo "${{steps.tag.outputs.tag}}"    
             
     - name: Split version code
       uses: xom9ikk/split@v1
       id: split
       with:
         string: v2022.2.1
         separator: .
         limit: -1
         

     - name: Some other action
       id: printv
       run: |
         echo "::set-output name=major::${{ steps.split.outputs._0 }}"  
         echo "::set-output name=minor::${{ steps.split.outputs._1 }}"  
         echo "::set-output name=patch::${{ steps.split.outputs._2 }}"             

             
       
       