name: Staging - Sync artifacts

on:
  push:
    branches:
      - 'PR-*'
      
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

